#!/usr/bin/python
# pip install pyocclient
# pip install clipboard
# pip install keyring
# pip install pync

import re
import os
import owncloud
import clipboard
import keyring
import hashlib
import time
from pync import Notifier
from subprocess import call

ownCloudURL = "https://gamma.rockstable.net/owncloud/" # Remember trailing /
ownCloudUserName = "john"

#-------------------------------------------------------------------------------

fileName = hashlib.md5(time.asctime(time.localtime(time.time()))).hexdigest()[:6] + ".png"
localPath = "/tmp/{}".format(fileName)
remotePath = "Screenshots/{}".format(fileName)

call("screencapture -i {}".format(localPath), shell=True)

oc = owncloud.Client(ownCloudURL)
password = keyring.get_password("owncloud", ownCloudUserName)
oc.login(ownCloudUserName, password)

if oc.put_file(remotePath, localPath):
    link = oc.share_file_with_link(remotePath)
    #uri = re.sub(r"index.php/", "", link.link)
    uri = ownCloudURL + "index.php/s/" + link.link.rsplit("=")[2]
    clipboard.copy(uri)
    Notifier.notify("Shared {}".format(fileName), title="Screenshot", group="screenie")
else:
    Notifier.notify("Failed to share {}".format(fileName), title="Screenshot", group="screenie")

os.remove(localPath)