#!/bin/bash

# Depends on jshon (brew install jshon)
# ${HOME}/.livestreamerrc needs the following
#
# twitch-oauth-token=<your token>
# default-stream=<desired stream quality> (like best, 720p, 480p, mobile, worst)
#

liveStreamerConfig=${HOME}/.livestreamerrc

colorOff='\033[0m'
yellow='\033[0;33m'
cyan='\033[0;36m'
red='\033[1;31m'
white='\033[1;37m'
green='\033[4;32m'

if [ ! -x "/usr/local/bin/jshon" ]
then
  echo
  echo -e "${red}Error:${colorOff} jshon is not installed."
  echo
  exit 1
fi

if [ ! -x "/usr/local/bin/livestreamer" ]
then
  echo
  echo -e "${red}Error:${colorOff} livestreamer is not installed."
  echo
  exit 1
fi

jshon="/usr/local/bin/jshon"
livestreamer="/usr/local/bin/livestreamer"

if [ -e ${liveStreamerConfig} ]
then
  twitchToken=$(grep "twitch-oauth-token" ${liveStreamerConfig} | cut -f 2 -d "=")
  liveStreamerQualitySetting=$(grep "default-stream" ${liveStreamerConfig} | cut -f 2 -d "=")

  if [ ! ${twitchToken} ]
  then
    echo
    echo -e "${red}Error:${colorOff} Could not find your Twitch Token from LiveStreamer config file."
    echo
    exit 1
  fi
else
  echo
  echo -e "${red}Error:${colorOff} Could not find ${liveStreamerConfig}."
  echo
  exit 1
fi

function cleanUp {
  rm ${streamTempFile}
}

streamOnlineFile="/tmp/twitch_notify"

if [ ! -f ${streamOnlineFile} ]
then
  echo "streamOnline=()" > ${streamOnlineFile}
fi

source ${streamOnlineFile}

streamTempFile=$(mktemp /tmp/twitch.XXXXXXXXXX)

curl -s -H "Accept: application/vnd.twitchtv.v3+json" \
   -H "Authorization: OAuth ${twitchToken}" \
   -X GET https://api.twitch.tv/kraken/streams/followed \
   | ${jshon} > ${streamTempFile}
streamFollowingTotal=$(cat ${streamTempFile} | ${jshon} -e _total)

i=0
streamOnlineTmp=()

while [ ${i} -lt ${streamFollowingTotal} ]
do
  streamFollowingName=$(cat ${streamTempFile} | ${jshon} -e streams -e ${i} -e channel -e name -u)
  streamFollowingGame=$(cat ${streamTempFile} | ${jshon} -e streams -e ${i} -e channel -e game -u)
  streamFollowingName2="$(tr '[:lower:]' '[:upper:]' <<< ${streamFollowingName:0:1})${streamFollowingName:1}"
  
  if [[ " ${streamOnline[@]} " =~ " ${streamFollowingName} " ]]
  then
    streamOnlineTmp+=(${streamFollowingName})
  else
    if [ -x /usr/local/bin/terminal-notifier ]
    then
      /usr/local/bin/terminal-notifier -title "Twitch broadcast" \
        -subtitle "${streamFollowingName2} is broadcasting now." \
        -message "Playing ${streamFollowingGame}" \
        -appIcon ${HOME}/.bin/twitch.png \
        -execute "${HOME}/.bin/twitch ${streamFollowingName}"
    else
      osascript -e 'display notification "'"Playing ${streamFollowingGame}"'" with title "'"${streamFollowingName2} is broadcasting now."'"'
    fi
    sleep 5
    streamOnlineTmp+=(${streamFollowingName})
  fi
  i=$[${i}+1]
done

echo "streamOnline=(${streamOnlineTmp[@]})" > ${streamOnlineFile}
cleanUp