#!/bin/bash

# Depends on jshon (brew install jshon)
# ${HOME}/.livestreamerrc needs the following
# 
# twitch-oauth-token=<your token>
# default-stream=<desired stream quality> (like best, 720p, 480p, mobile, worst)
#

clear

liveStreamerConfig=${HOME}/.livestreamerrc

if [ ! -e "/usr/local/bin/jshon" ];
then
  echo "jshon is not installed."
  exit 1
fi

if [ -e ${liveStreamerConfig} ];
then
  twitchToken=$(grep "twitch-oauth-token" ${liveStreamerConfig} | cut -f 2 -d "=")
  liveStreamerQualitySetting=$(grep "default-stream" ${liveStreamerConfig} | cut -f 2 -d "=")

  if [ ! ${twitchToken} ];
  then
    echo "Could not find your Twitch Token from LiveStreamer config file."
    exit 1
  fi

  if [ ${liveStreamerQualitySetting} ]
  then
    liveStreamerQuality=${liveStreamerQualitySetting}
  else
    echo "You need to set default-stream setting in your ${HOME}/.livestreamerrc"
    echo "Setting your stream quality to worst."
    liveStreamerQuality="worst"
  fi
fi

function openStream {
  livestreamer -Q -p "/Applications/VLC.app/Contents/MacOS/VLC --file-caching=5000" --twitch-oauth-token ${twitchToken}${1} ${liveStreamerQuality}
}

streamTempFile=$(mktemp /tmp/twitch.XXXXXXXXXX)

curl -s -H "Accept: application/vnd.twitchtv.v3+json" \
   -H "Authorization: OAuth ${twitchToken}" -X GET https://api.twitch.tv/kraken/streams/followed \
   | jshon > ${streamTempFile}

streamFollowingTotal=$(cat ${streamTempFile} | jshon -e _total)

if [ ${streamFollowingTotal} -eq 0 ];
  then
  echo "No streamers followed are live right now."
  exit 0
fi

i=0
echo
echo "Streamers live right now:"

while [ ${i} -lt ${streamFollowingTotal} ]
do
  streamFollowingName=$(cat ${streamTempFile} | jshon -e streams -e ${i} -e channel -e name | tr -d '"')
  streamFollowingGame=$(cat ${streamTempFile} | jshon -e streams -e ${i} -e channel -e game | tr -d '"')  
  echo "  $[${i}+1]) ${streamFollowingName} (playing ${streamFollowingGame})"
  i=$[${i}+1]
done

read streamToWatch

if [[ ! ${streamToWatch} =~ ^[0-9]+$ ]];
then
  exit 0
fi

streamToWatch=$[${streamToWatch}-1]
streamFollowingUrl=$(cat ${streamTempFile} | jshon -e streams -e ${streamToWatch} -e channel -e url | tr -d '"')

openStream ${streamFollowingUrl}

rm ${streamTempFile}
echo