#!/bin/bash

function openstream {
  livestreamer -Q -p "/Applications/VLC.app/Contents/MacOS/VLC --file-caching=5000" http://twitch.tv/${1} ${quality}
}

if [ ${2} ]
then
  quality="${2}"
else
  quality="best"
fi

if [ ! ${1} ]
then

  echo "1) Zisteau"
  echo "2) Squirrel"
  echo "3) JayzTwoCents"
  echo "4) Barnacules"
  echo "5) Einarjh"
  echo "6) Sjokomelk"

  read stream

  case ${stream} in
    1)  openstream zisteau
        ;;
    2)  openstream squirrel
        ;;
    3)  openstream jaysvfx
        ;;
    4)  openstream barnacules
        ;;
    5)  openstream einarjh
        ;;
    6)  openstream sjokomelk
        ;;

  esac

else
  openstream ${1}
fi
